global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: apiservices
    metrics_path: /metrics
    static_configs: 
      - targets: 
        - 'prometheus:9090'
        - 'api:5069'

remote_write:
      - url: https://prometheus-us-central1.grafana.net/api/prom/push
        basic_auth:
          username: 793618
          password: eyJrIjoiMDNmNTU2NzQyYTdkOWIyYTE1ZDNhNTJlYWJjMTQ3MzlmNDdjZDgxYSIsIm4iOiJ2aWRlb19nYW1lX21ldHJpY3MiLCJpZCI6ODAzMjQwfQ==
